kind: pipeline
type: docker
name: build

clone:
  disable: false
  depth: 1

steps:
  - name: golangci-lint
    image: golangci/golangci-lint
    pull: if-not-exist
    commands:
      - golangci-lint run

  - name: go build
    image: golang:1.19
    pull: if-not-exist
    commands:
      - go mod tidy
      - go build .

  - name: go test
    image: golang:1.19
    pull: if-not-exist
    commands:
      - go test -v ./...

  - name: go bench test
    image: golang:1.19
    pull: if-not-exist
    commands:
      - go test -v -bench=./ -run=^$

  - name: feishu notification
    image: serialt/drone-feishu-message
    pull: if-not-exists
    settings:
      token:
        from_secret: notification_token
      sha_link: true
    when:
      status: [ failure, success ]