kind: pipeline
type: docker
name: build

clone:
  disable: false
  depth: 1

steps:
  - name: linter
    image: golang:latest
    pull: if-not-exist
    commands:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@1.47.2
      - golangci-lint run

  - name: build
    image: golang:1.19
    pull: if-not-exist
    commands:
      - go mod tidy
      - go build .

  - name: unit test
    image: golang:1.19
    pull: if-not-exist
    commands:
      - go test -v ./...

  - name: benchmark test
    image: golang:1.19
    pull: if-not-exist
    commands:
      - go test -v -bench=./ -run=^$

  - name: notification
    image: serialt/drone-feishu-message
    pull: if-not-exists
    settings:
      token:
        from_secret: notification_token
      sha_link: true
    when:
      status: [ failure, success ]